// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

import {
  nsZenPreloadedFeature,
  nsZenMultiWindowFeature,
} from "chrome://browser/content/zen-components/ZenCommonUtils.mjs";

const DOT_RE = /\./g;
const WHITESPACE_RE = /\s/g;
const NON_NAME_RE = /[^A-Za-z_-]+/g;

/**
 * Zen Mods Manager, handles downloading, updating and applying Zen Mods.
 *
 * @augments nsZenPreloadedFeature
 */
class nsZenMods extends nsZenPreloadedFeature {
  // private properties start
  #kZenStylesheetModHeader = "/* Zen Mods - Generated by ZenMods.";
  #kZenStylesheetModHeaderBody = `* DO NOT EDIT THIS FILE DIRECTLY!
* Your changes will be overwritten.
* Instead, go to the preferences and edit the mods there.
*/
`;
  #kZenStylesheetModFooter = `
/* End of Zen Mods */
`;
  #getCurrentDateTime = () =>
    new Intl.DateTimeFormat("en-US", {
      dateStyle: "full",
      timeStyle: "full",
    }).format(new Date().getTime());

  constructor() {
    super();
  }

  // Stylesheet service
  #_modsBackend = null;

  get #modsBackend() {
    if (!this.#_modsBackend) {
      this.#_modsBackend = Cc["@mozilla.org/zen/mods-backend;1"].getService(
        Ci.nsIZenModsBackend
      );
    }
    return this.#_modsBackend;
  }

  get #styleSheetPath() {
    return PathUtils.join(PathUtils.profileDir, "chrome", "zen-themes.css");
  }

  async #handleDisableMods() {
    await this.#rebuildModsStylesheet();
  }

  #getStylesheetPathForMod(mod) {
    return PathUtils.join(this.getModFolder(mod.id), "chrome.css");
  }

  async #readStylesheet() {
    const path = this.modsRootPath;
    if (!(await IOUtils.exists(path))) {
      return "";
    }
    return await IOUtils.readUTF8(this.#styleSheetPath);
  }

  async #insertStylesheet() {
    try {
      const content = await this.#readStylesheet();
      this.#modsBackend.rebuildModsStyles(content);
    } catch (e) {
      console.warn("[ZenMods]: Error rebuilding mods styles:", e);
    }
  }

  async #rebuildModsStylesheet() {
    const mods = await this.#getEnabledMods();

    await this.#writeStylesheet(mods);

    const modsWithPreferences = await Promise.all(
      mods.map(async mod => {
        const preferences = await this.getModPreferences(mod);

        return {
          name: mod.name,
          enabled: mod.enabled,
          preferences,
        };
      })
    );

    this.#setDefaults(modsWithPreferences);
    this.#writeToDom(modsWithPreferences);

    await this.#insertStylesheet();
  }

  async #getEnabledMods() {
    if (Services.prefs.getBoolPref("zen.themes.disable-all", false)) {
      // eslint-disable-next-line no-console
      console.info("[ZenMods]: Mods are disabled by user preference.");
      return [];
    }
    const modsObject = await this.getMods();
    const mods = Object.values(modsObject).filter(
      mod => mod.enabled === undefined || mod.enabled
    );

    // eslint-disable-next-line no-shadow
    const modList = mods.map(({ name }) => name).join(", ");

    const message =
      modList !== ""
        ? `[ZenMods]: Loading enabled Zen mods: ${modList}.`
        : "[ZenMods]: No enabled Zen mods.";

    console.warn(message);

    return mods;
  }

  #setDefaults(modsWithPreferences) {
    for (const { preferences, enabled } of modsWithPreferences) {
      if (enabled !== undefined && !enabled) {
        continue;
      }

      for (const { type, property, defaultValue } of preferences) {
        if (defaultValue === undefined) {
          continue;
        }

        const getProperty =
          type === "checkbox"
            ? Services.prefs.getBoolPref
            : Services.prefs.getStringPref;
        const setProperty =
          type === "checkbox"
            ? Services.prefs.setBoolPref
            : Services.prefs.setStringPref;

        try {
          getProperty(property);
        } catch {
          console.warn(
            `[ZenMods]: Setting default value for ${property} to ${defaultValue} (${typeof defaultValue})`
          );

          if (
            typeof defaultValue !== "boolean" &&
            typeof defaultValue !== "string" &&
            typeof defaultValue !== "number"
          ) {
            console.warn(
              `[ZenMods]: Warning, invalid data type received (${typeof defaultValue}), skipping.`
            );
            continue;
          }

          setProperty(
            property,
            typeof defaultValue === "boolean"
              ? defaultValue
              : defaultValue.toString()
          );
        }
      }
    }
  }

  #writeToDom(modsWithPreferences) {
    // Precompute per-mod data once; values are global prefs and sanitized
    // names don't vary per browser window, so this hoists O(windows) work.
    const prepared = modsWithPreferences.map(
      // eslint-disable-next-line no-shadow
      ({ enabled, preferences, name }) => ({
        enabled,
        sanitizedName: this.sanitizeModName(name),
        prefs: preferences.map(({ property, type }) => {
          const isEnabled = enabled === undefined || enabled;
          const getPref =
            type === "checkbox"
              ? Services.prefs.getBoolPref
              : Services.prefs.getStringPref;
          const fallback = type === "checkbox" ? false : "";

          return {
            property,
            type,
            sanitizedProperty: property?.replaceAll(DOT_RE, "-"),
            value: isEnabled ? getPref(property, fallback) : fallback,
          };
        }),
      })
    );

    for (const browser of nsZenMultiWindowFeature.browsers) {
      const doc = browser.document;
      const root = doc.documentElement;

      for (const { enabled, sanitizedName, prefs } of prepared) {
        if (enabled !== undefined && !enabled) {
          const element = doc.getElementById(sanitizedName);
          if (element) {
            element.remove();
          }

          for (const { type, sanitizedProperty } of prefs) {
            if (type === "checkbox") {
              continue;
            }
            root.style.removeProperty(`--${sanitizedProperty}`);
          }

          continue;
        }

        for (const { type, sanitizedProperty, value } of prefs) {
          switch (type) {
            case "dropdown": {
              if (value !== "") {
                let element = doc.getElementById(sanitizedName);

                if (!element) {
                  element = doc.createElement("div");
                  element.style.display = "none";
                  element.setAttribute("id", sanitizedName);
                  doc.body.appendChild(element);
                }

                element.setAttribute(sanitizedProperty, value);
              }
              break;
            }

            case "string": {
              if (value === "") {
                root.style.removeProperty(`--${sanitizedProperty}`);
              } else {
                root.style.setProperty(`--${sanitizedProperty}`, value);
              }
              break;
            }
          }
        }
      }
    }
  }

  async #writeStylesheet(modList = []) {
    const mods = [];

    for (let mod of modList) {
      mod._filePath = this.#getStylesheetPathForMod(mod);
      mods.push(mod);
    }

    let content = this.#kZenStylesheetModHeader;
    content += `\n* FILE GENERATED AT: ${this.#getCurrentDateTime()}\n`;
    content += this.#kZenStylesheetModHeaderBody;

    for (let mod of mods) {
      if (mod.enabled !== undefined && !mod.enabled) {
        continue;
      }

      content += `\n/* Name: ${mod.name} */\n`;
      content += `/* Description: ${mod.description} */\n`;
      content += `/* Author: @${mod.author} */\n`;

      if (mod._readmeURL) {
        content += `/* Readme: ${mod.readme} */\n`;
      }

      const chromeContent = await IOUtils.readUTF8(mod._filePath);
      content += chromeContent;
    }

    content += this.#kZenStylesheetModFooter;

    const buffer = new TextEncoder().encode(content);

    await IOUtils.write(this.#styleSheetPath, buffer);
  }

  async #downloadUrlToFile(url, path, maxRetries = 3, retryDelayMs = 500) {
    // Mod assets must come over HTTPS. Without a signing/hash scheme this
    // is the minimum guard against MITM or a store-hosted HTTP redirect
    // serving attacker-controlled CSS/JSON into the chrome profile.
    let parsed;
    try {
      parsed = new URL(url);
    } catch {
      throw new Error(`[ZenMods]: Invalid mod asset URL: ${url}`);
    }
    if (parsed.protocol !== "https:") {
      throw new Error(`[ZenMods]: Refusing non-HTTPS mod asset URL: ${url}`);
    }

    let attempt = 0;

    while (attempt < maxRetries) {
      try {
        const response = await fetch(url);

        if (!response.ok) {
          throw new Error(
            `HTTP error! status: ${response.status} for url: ${url}`
          );
        }

        const data = await response.text();

        // convert the data into a Uint8Array
        const buffer = new TextEncoder().encode(data);
        await IOUtils.write(path, buffer);

        return; // to exit the loop
      } catch (e) {
        attempt++;
        if (attempt >= maxRetries) {
          console.error(
            "[ZenMods]: Error downloading file after retries",
            url,
            e
          );
        } else {
          console.warn(
            `[ZenMods]: Download failed (attempt ${attempt} of ${maxRetries}), retrying in ${retryDelayMs}ms...`,
            url,
            e
          );
          await new Promise(res => setTimeout(res, retryDelayMs));
        }
      }
    }
  }

  // private properties end

  // public properties start

  throttle(mainFunction, delay) {
    let timerFlag = null;

    return (...args) => {
      if (timerFlag === null) {
        mainFunction(...args);
        timerFlag = setTimeout(() => {
          timerFlag = null;
        }, delay);
      }
    };
  }

  debounce(mainFunction, wait) {
    let timerFlag;

    return (...args) => {
      clearTimeout(timerFlag);
      timerFlag = setTimeout(() => {
        mainFunction(...args);
      }, wait);
    };
  }

  sanitizeModName(aName) {
    // Do not change to "mod-" for backwards compatibility
    return `theme-${aName?.replaceAll(WHITESPACE_RE, "-")?.replaceAll(NON_NAME_RE, "")}`;
  }

  get updatePref() {
    return "zen.mods.updated-value-observer";
  }

  get modsRootPath() {
    return PathUtils.join(PathUtils.profileDir, "chrome", "zen-themes");
  }

  get modsDataFile() {
    return PathUtils.join(PathUtils.profileDir, "zen-themes.json");
  }

  getModFolder(modId) {
    return PathUtils.join(this.modsRootPath, modId);
  }

  async getMods() {
    if (!(await IOUtils.exists(this.modsDataFile))) {
      await IOUtils.writeJSON(this.modsDataFile, {});

      return {};
    }

    let mods = {};

    try {
      mods = await IOUtils.readJSON(this.modsDataFile);

      if (mods === null || typeof mods !== "object") {
        throw new Error("Mods data file is invalid");
      }
    } catch {
      // If we have a corrupted file, reset it
      await IOUtils.writeJSON(this.modsDataFile, {});

      Services.wm
        .getMostRecentWindow("navigator:browser")
        .gZenUIManager.showToast("zen-themes-corrupted", {
          timeout: 8000,
        });
    }

    return mods;
  }

  async getModPreferences(mod) {
    const modPath = PathUtils.join(
      this.modsRootPath,
      mod.id,
      "preferences.json"
    );

    if (!(await IOUtils.exists(modPath)) || !mod.preferences) {
      return [];
    }

    try {
      const preferences = await IOUtils.readJSON(modPath);

      return preferences.filter(({ disabledOn = [] }) => {
        return !disabledOn.includes(
          gZenOperatingSystemCommonUtils.currentOperatingSystem
        );
      });
    } catch (e) {
      console.error(
        `[ZenMods]: Error reading mod preferences for ${mod.name}:`,
        e
      );
      return [];
    }
  }

  async init() {
    try {
      await SessionStore.promiseInitialized;

      if (
        Services.prefs.getBoolPref("zen.themes.disable-all", false) ||
        Services.appinfo.inSafeMode
      ) {
        console.warn("[ZenMods]: Mods disabled by user or in safe mode.");
        return;
      }

      await this.getMods(); // Check for any errors in the themes data file
      const mods = await this.#getEnabledMods();

      const modsWithPreferences = await Promise.all(
        mods.map(async mod => {
          const preferences = await this.getModPreferences(mod);

          return {
            name: mod.name,
            enabled: mod.enabled,
            preferences,
          };
        })
      );

      this.#writeToDom(modsWithPreferences);

      await this.#insertStylesheet();

      this.#setNewMilestoneIfNeeded();
    } catch (e) {
      console.error("[ZenMods]: Error loading Zen Mods:", e);
    }

    const rebuildObserver = this.#rebuildModsStylesheet.bind(this);
    const disableObserver = this.#handleDisableMods.bind(this);
    Services.prefs.addObserver(this.updatePref, rebuildObserver);
    Services.prefs.addObserver("zen.themes.disable-all", disableObserver);
    window.addEventListener(
      "unload",
      () => {
        Services.prefs.removeObserver(this.updatePref, rebuildObserver);
        Services.prefs.removeObserver(
          "zen.themes.disable-all",
          disableObserver
        );
      },
      { once: true }
    );
  }

  #setNewMilestoneIfNeeded() {
    const previousMilestone = Services.prefs.getStringPref(
      "zen.mods.milestone",
      ""
    );
    if (previousMilestone != Services.appinfo.version) {
      Services.prefs.setStringPref(
        "zen.mods.milestone",
        Services.appinfo.version
      );
      Services.prefs.clearUserPref("zen.mods.last-update");
    }
  }

  async removeMod(modId, triggerUpdate = true) {
    const modPath = this.getModFolder(modId);

    console.warn(`[ZenMods]: Removing mod ${modPath}`);

    await IOUtils.remove(modPath, { recursive: true, ignoreAbsent: true });

    const mods = await this.getMods();

    delete mods[modId];

    await IOUtils.writeJSON(this.modsDataFile, mods);

    if (triggerUpdate) {
      this.triggerModsUpdate();
    }
  }

  async enableMod(modId) {
    const mods = await this.getMods();
    const mod = mods[modId];

    console.warn(`[ZenMods]: Enabling mod ${mod.name}`);

    mod.enabled = true;

    await IOUtils.writeJSON(this.modsDataFile, mods);
  }

  async disableMod(modId) {
    const mods = await this.getMods();
    const mod = mods[modId];

    console.warn(`[ZenMods]: Disabling mod ${mod.name}`);

    mod.enabled = false;

    await IOUtils.writeJSON(this.modsDataFile, mods);
  }

  async updateMods(mods = undefined) {
    if (!mods) {
      mods = await this.getMods();
    }

    await IOUtils.writeJSON(this.modsDataFile, mods);
    await this.checkForModChanges();
  }

  triggerModsUpdate() {
    Services.prefs.setBoolPref(
      this.updatePref,
      !Services.prefs.getBoolPref(this.updatePref)
    );
  }

  async installMod(mod) {
    try {
      const modPath = PathUtils.join(this.modsRootPath, mod.id);
      await IOUtils.makeDirectory(modPath, { ignoreExisting: true });

      await this.#downloadUrlToFile(
        mod.style,
        PathUtils.join(modPath, "chrome.css")
      );
      await this.#downloadUrlToFile(
        mod.readme,
        PathUtils.join(modPath, "readme.md")
      );

      if (mod.preferences) {
        await this.#downloadUrlToFile(
          mod.preferences,
          PathUtils.join(modPath, "preferences.json")
        );
      }
    } catch (e) {
      console.error("[ZenMods]: Error installing mod", mod.id, e);
    }
  }

  async checkForModChanges() {
    const mods = await this.getMods();

    for (const [modId, mod] of Object.entries(mods)) {
      try {
        if (!mod) {
          continue;
        }

        if (!(await IOUtils.exists(this.getModFolder(modId)))) {
          await this.installMod(mod);
        }
      } catch (e) {
        console.error("[ZenMods]: Error checking for mod changes", e);
      }
    }

    this.triggerModsUpdate();
  }

  async isModInstalled(modId) {
    const mods = await this.getMods();
    return Boolean(mods?.[modId]);
  }

  // public properties end
}

window.gZenMods = new nsZenMods();
